# Generated by Django 6.0.1 on 2026-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_autoset',
            field=models.BooleanField(default=False),
        ),
    ]
